### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by nkwang24** [uclahs-cds/pipeline-StableLift#16]
Any additional considerations before we open up the repo? @nwiltsie @yashpatel6 @tyamaguchi-ucla 

Once public and finalized, I will follow https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content to make the repo citable.

**Comment by nwiltsie** [comment]
The repo is now public.

The associated image is _not_ yet - I ran into a weird error:
https://github.com/orgs/uclahs-cds/packages/container/stablelift/settings

<img width="478" alt="Screenshot 2024-08-30 at 5 45 20 PM" src="https://github.com/user-attachments/assets/746e2843-8709-4d8a-b74e-510fd6345851">

@yashpatel6, any idea what's up with that?

**Comment by yashpatel6** [comment]
> The repo is now public.
> 
> The associated image is _not_ yet - I ran into a weird error: https://github.com/orgs/uclahs-cds/packages/container/stablelift/settings
> <img alt="Screenshot 2024-08-30 at 5 45 20 PM" width="478" src="https://private-user-images.githubusercontent.com/829731/363369123-746e2843-8709-4d8a-b74e-510fd6345851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzI2NTQsIm5iZiI6MTcyNTA3MjM1NCwicGF0aCI6Ii84Mjk3MzEvMzYzMzY5MTIzLTc0NmUyODQzLTg3MDktNGQ4YS1iNzRlLTUxMGZkNjM0NTg1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwMjQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTdmYTRhYTM4OGUzM2Q2NTY2NTQ0ZTdlYzljNGFhZTNiOTRiOWViZjBmYTVlMzg5YzE3ZjRkMTA4OGRlZGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.klgwo8l6kwuiUVZNbKYlKTcPDkl8wkhbv309X_LTNjY">
> 
> @yashpatel6, any idea what's up with that?

Ah yes, by default the option to make images public is disabled so the permission has to be enabled temporarily, the image made public, and then permission reverted. I've gone ahead and made the image public.
